-- LUMINA durable learning persistence (prepared; not activated until a dedicated project is configured).
-- Server-side access only: do not expose secret/service-role keys to the browser.

create table if not exists public.lumina_learning_attempts (
    id bigint generated by default as identity primary key,
    learner_key text not null,
    module_id text,
    unit_id text,
    lesson_id text not null,
    check_id text,
    evidence_id text,
    answer text,
    correct boolean,
    source_pages text,
    activity_type text,
    created_at timestamptz not null default now()
);

create index if not exists lumina_attempts_learner_lesson_idx
    on public.lumina_learning_attempts (learner_key, lesson_id, created_at);

create table if not exists public.lumina_mistakes (
    id bigint generated by default as identity primary key,
    learner_key text not null,
    module_id text,
    unit_id text,
    lesson_id text not null,
    lesson_title text,
    check_id text not null,
    question text,
    answer text,
    mistake_type text,
    hint text,
    source_pages text,
    resolved boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resolved_at timestamptz,
    unique (learner_key, lesson_id, check_id)
);

create index if not exists lumina_mistakes_learner_idx
    on public.lumina_mistakes (learner_key, resolved, updated_at);

create table if not exists public.lumina_reviews (
    id bigint generated by default as identity primary key,
    learner_key text not null,
    module_id text,
    lesson_id text not null,
    lesson_title text,
    check_id text not null,
    status text not null default 'due',
    reason text,
    source_pages text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (learner_key, lesson_id, check_id)
);

create index if not exists lumina_reviews_learner_status_idx
    on public.lumina_reviews (learner_key, status, updated_at);

create table if not exists public.lumina_profile_state (
    learner_key text primary key,
    state jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.lumina_learning_attempts enable row level security;
alter table public.lumina_mistakes enable row level security;
alter table public.lumina_reviews enable row level security;
alter table public.lumina_profile_state enable row level security;

revoke all on public.lumina_learning_attempts from anon, authenticated;
revoke all on public.lumina_mistakes from anon, authenticated;
revoke all on public.lumina_reviews from anon, authenticated;
revoke all on public.lumina_profile_state from anon, authenticated;

grant select, insert, update, delete on public.lumina_learning_attempts to service_role;
grant select, insert, update, delete on public.lumina_mistakes to service_role;
grant select, insert, update, delete on public.lumina_reviews to service_role;
grant select, insert, update, delete on public.lumina_profile_state to service_role;
grant usage, select on all sequences in schema public to service_role;
