from __future__ import annotations

from typing import Protocol


class LearningStore(Protocol):
    def record_attempt(self, attempt: dict) -> None: ...
    def get_attempts(self, lesson_id: str | None = None) -> list[dict]: ...

    def record_mistake(self, mistake: dict) -> None: ...
    def resolve_mistake(self, lesson_id: str, check_id: str) -> None: ...
    def get_mistakes(
        self,
        lesson_id: str | None = None,
        unresolved_only: bool = False,
    ) -> list[dict]: ...

    def queue_review(self, review: dict) -> None: ...
    def complete_review(self, lesson_id: str, check_id: str) -> None: ...
    def get_reviews(self, status: str | None = None) -> list[dict]: ...
