-- LUMINA NOUR durable learning persistence for Neon PostgreSQL.
-- Apply this once in the dedicated LUMINA NOUR database.
-- The database connection string must remain server-side in Streamlit secrets.

create table if not exists lumina_learning_attempts (
    id bigint generated by default as identity primary key,
    learner_key text not null,
    module_id text,
    unit_id text,
    lesson_id text not null,
    check_id text,
    evidence_id text,
    answer text,
    correct boolean,
    source_pages text,
    activity_type text,
    created_at timestamptz not null default now()
);

create index if not exists lumina_attempts_learner_lesson_idx
    on lumina_learning_attempts (learner_key, lesson_id, created_at);

create table if not exists lumina_mistakes (
    id bigint generated by default as identity primary key,
    learner_key text not null,
    module_id text,
    unit_id text,
    lesson_id text not null,
    lesson_title text,
    check_id text not null,
    question text,
    answer text,
    mistake_type text,
    hint text,
    source_pages text,
    resolved boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resolved_at timestamptz,
    unique (learner_key, lesson_id, check_id)
);

create index if not exists lumina_mistakes_learner_idx
    on lumina_mistakes (learner_key, resolved, updated_at);

create table if not exists lumina_reviews (
    id bigint generated by default as identity primary key,
    learner_key text not null,
    module_id text,
    lesson_id text not null,
    lesson_title text,
    check_id text not null,
    status text not null default 'due',
    reason text,
    source_pages text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (learner_key, lesson_id, check_id)
);

create index if not exists lumina_reviews_learner_status_idx
    on lumina_reviews (learner_key, status, updated_at);

create table if not exists lumina_profile_state (
    learner_key text primary key,
    state jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);


-- Permanent trusted-source catalog.
-- Large PDF/image bytes live in a durable object/file provider; Neon stores
-- metadata and provenance only.
create table if not exists lumina_trusted_sources (
    source_id text primary key,
    learner_key text not null,
    filename text not null,
    display_name text not null,
    subject text not null,
    term_label text not null,
    unit_label text,
    mime_type text not null,
    sha256 text not null,
    size_bytes bigint not null check (size_bytes > 0),
    storage_provider text not null,
    storage_key text not null,
    trust_status text not null default 'trusted'
        check (trust_status in ('trusted', 'archived')),
    active boolean not null default true,
    notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (learner_key, sha256)
);

create index if not exists lumina_trusted_sources_lookup_idx
    on lumina_trusted_sources (learner_key, subject, active, updated_at);
